version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: budget-buddy-db
    environment:
      - MYSQL_DATABASE=budget-buddy
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    restart: always