CREATE TABLE users_children(
   id INT AUTO_INCREMENT,
   user_id INT,
   user_children INT,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (id, user_id),
   FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE CASCADE,
   FOREIGN KEY (user_children) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE CASCADE
);