CREATE TABLE users_parent(
     id INT AUTO_INCREMENT,
     user_id INT,
     user_parent INT,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (id, user_id),
     FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE CASCADE,
     FOREIGN KEY (user_parent) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE CASCADE
);